let data = [
 {
   "Game": 1,
   "Date": "Wed Oct 17 2018",
   "Location": "",
   "Opponent": "Atlanta Hawks",
   "Result": "W",
   "TeamScore": 126,
   "OpponentScore": 107,
   "W": 1,
   "L": 0
 },
 {
   "Game": 2,
   "Date": "Fri Oct 19 2018",
   "Location": "@",
   "Opponent": "Brooklyn Nets",
   "Result": "L",
   "TeamScore": 105,
   "OpponentScore": 107,
   "W": 1,
   "L": 1
 },
 {
   "Game": 3,
   "Date": "Sat Oct 20 2018",
   "Location": "",
   "Opponent": "Boston Celtics",
   "Result": "L",
   "TeamScore": 101,
   "OpponentScore": 103,
   "W": 1,
   "L": 2
 },
 {
   "Game": 4,
   "Date": "Mon Oct 22 2018",
   "Location": "@",
   "Opponent": "Milwaukee Bucks",
   "Result": "L",
   "TeamScore": 113,
   "OpponentScore": 124,
   "W": 1,
   "L": 3
 },
 {
   "Game": 5,
   "Date": "Wed Oct 24 2018",
   "Location": "@",
   "Opponent": "Miami Heat",
   "Result": "L",
   "TeamScore": 87,
   "OpponentScore": 110,
   "W": 1,
   "L": 4
 },
 {
   "Game": 6,
   "Date": "Fri Oct 26 2018",
   "Location": "",
   "Opponent": "Golden State Warriors",
   "Result": "L",
   "TeamScore": 100,
   "OpponentScore": 128,
   "W": 1,
   "L": 5
 },
 {
   "Game": 7,
   "Date": "Mon Oct 29 2018",
   "Location": "",
   "Opponent": "Brooklyn Nets",
   "Result": "W",
   "TeamScore": 115,
   "OpponentScore": 96,
   "W": 2,
   "L": 5
 },
 {
   "Game": 8,
   "Date": "Wed Oct 31 2018",
   "Location": "",
   "Opponent": "Indiana Pacers",
   "Result": "L",
   "TeamScore": 101,
   "OpponentScore": 107,
   "W": 2,
   "L": 6
 },
 {
   "Game": 9,
   "Date": "Fri Nov 2 2018",
   "Location": "@",
   "Opponent": "Dallas Mavericks",
   "Result": "W",
   "TeamScore": 118,
   "OpponentScore": 106,
   "W": 3,
   "L": 6
 },
 {
   "Game": 10,
   "Date": "Sun Nov 4 2018",
   "Location": "@",
   "Opponent": "Washington Wizards",
   "Result": "L",
   "TeamScore": 95,
   "OpponentScore": 108,
   "W": 3,
   "L": 7
 },
 {
   "Game": 11,
   "Date": "Mon Nov 5 2018",
   "Location": "",
   "Opponent": "Chicago Bulls",
   "Result": "L",
   "TeamScore": 115,
   "OpponentScore": 116,
   "W": 3,
   "L": 8
 },
 {
   "Game": 12,
   "Date": "Wed Nov 7 2018",
   "Location": "@",
   "Opponent": "Atlanta Hawks",
   "Result": "W",
   "TeamScore": 112,
   "OpponentScore": 107,
   "W": 4,
   "L": 8
 },
 {
   "Game": 13,
   "Date": "Sat Nov 10 2018",
   "Location": "@",
   "Opponent": "Toronto Raptors",
   "Result": "L",
   "TeamScore": 112,
   "OpponentScore": 128,
   "W": 4,
   "L": 9
 },
 {
   "Game": 14,
   "Date": "Sun Nov 11 2018",
   "Location": "",
   "Opponent": "Orlando Magic",
   "Result": "L",
   "TeamScore": 89,
   "OpponentScore": 115,
   "W": 4,
   "L": 10
 },
 {
   "Game": 15,
   "Date": "Wed Nov 14 2018",
   "Location": "@",
   "Opponent": "Oklahoma City Thunder",
   "Result": "L",
   "TeamScore": 103,
   "OpponentScore": 128,
   "W": 4,
   "L": 11
 },
 {
   "Game": 16,
   "Date": "Fri Nov 16 2018",
   "Location": "@",
   "Opponent": "New Orleans Pelicans",
   "Result": "L",
   "TeamScore": 124,
   "OpponentScore": 129,
   "W": 4,
   "L": 12
 },
 {
   "Game": 17,
   "Date": "Sun Nov 18 2018",
   "Location": "@",
   "Opponent": "Orlando Magic",
   "Result": "L",
   "TeamScore": 117,
   "OpponentScore": 131,
   "W": 4,
   "L": 13
 },
 {
   "Game": 18,
   "Date": "Tue Nov 20 2018",
   "Location": "",
   "Opponent": "Portland Trail Blazers",
   "Result": "L",
   "TeamScore": 114,
   "OpponentScore": 118,
   "W": 4,
   "L": 14
 },
 {
   "Game": 19,
   "Date": "Wed Nov 21 2018",
   "Location": "@",
   "Opponent": "Boston Celtics",
   "Result": "W",
   "TeamScore": 117,
   "OpponentScore": 109,
   "W": 5,
   "L": 14
 },
 {
   "Game": 20,
   "Date": "Fri Nov 23 2018",
   "Location": "",
   "Opponent": "New Orleans Pelicans",
   "Result": "W",
   "TeamScore": 114,
   "OpponentScore": 109,
   "W": 6,
   "L": 14
 },
 {
   "Game": 21,
   "Date": "Sun Nov 25 2018",
   "Location": "@",
   "Opponent": "Memphis Grizzlies",
   "Result": "W",
   "TeamScore": 103,
   "OpponentScore": 98,
   "W": 7,
   "L": 14
 },
 {
   "Game": 22,
   "Date": "Tue Nov 27 2018",
   "Location": "@",
   "Opponent": "Detroit Pistons",
   "Result": "L",
   "TeamScore": 108,
   "OpponentScore": 115,
   "W": 7,
   "L": 15
 },
 {
   "Game": 23,
   "Date": "Wed Nov 28 2018",
   "Location": "@",
   "Opponent": "Philadelphia 76ers",
   "Result": "L",
   "TeamScore": 91,
   "OpponentScore": 117,
   "W": 7,
   "L": 16
 },
 {
   "Game": 24,
   "Date": "Sat Dec 1 2018",
   "Location": "",
   "Opponent": "Milwaukee Bucks",
   "Result": "W",
   "TeamScore": 136,
   "OpponentScore": 134,
   "W": 8,
   "L": 16
 },
 {
   "Game": 25,
   "Date": "Mon Dec 3 2018",
   "Location": "",
   "Opponent": "Washington Wizards",
   "Result": "L",
   "TeamScore": 107,
   "OpponentScore": 110,
   "W": 8,
   "L": 17
 },
 {
   "Game": 26,
   "Date": "Thu Dec 6 2018",
   "Location": "@",
   "Opponent": "Boston Celtics",
   "Result": "L",
   "TeamScore": 100,
   "OpponentScore": 128,
   "W": 8,
   "L": 18
 },
 {
   "Game": 27,
   "Date": "Sat Dec 8 2018",
   "Location": "",
   "Opponent": "Brooklyn Nets",
   "Result": "L",
   "TeamScore": 104,
   "OpponentScore": 112,
   "W": 8,
   "L": 19
 },
 {
   "Game": 28,
   "Date": "Sun Dec 9 2018",
   "Location": "",
   "Opponent": "Charlotte Hornets",
   "Result": "L",
   "TeamScore": 107,
   "OpponentScore": 119,
   "W": 8,
   "L": 20
 },
 {
   "Game": 29,
   "Date": "Wed Dec 12 2018",
   "Location": "@",
   "Opponent": "Cleveland Cavaliers",
   "Result": "L",
   "TeamScore": 106,
   "OpponentScore": 113,
   "W": 8,
   "L": 21
 },
 {
   "Game": 30,
   "Date": "Fri Dec 14 2018",
   "Location": "@",
   "Opponent": "Charlotte Hornets",
   "Result": "W",
   "TeamScore": 126,
   "OpponentScore": 124,
   "W": 9,
   "L": 21
 },
 {
   "Game": 31,
   "Date": "Sun Dec 16 2018",
   "Location": "@",
   "Opponent": "Indiana Pacers",
   "Result": "L",
   "TeamScore": 99,
   "OpponentScore": 110,
   "W": 9,
   "L": 22
 },
 {
   "Game": 32,
   "Date": "Mon Dec 17 2018",
   "Location": "",
   "Opponent": "Phoenix Suns",
   "Result": "L",
   "TeamScore": 110,
   "OpponentScore": 128,
   "W": 9,
   "L": 23
 },
 {
   "Game": 33,
   "Date": "Wed Dec 19 2018",
   "Location": "@",
   "Opponent": "Philadelphia 76ers",
   "Result": "L",
   "TeamScore": 109,
   "OpponentScore": 131,
   "W": 9,
   "L": 24
 },
 {
   "Game": 34,
   "Date": "Fri Dec 21 2018",
   "Location": "",
   "Opponent": "Atlanta Hawks",
   "Result": "L",
   "TeamScore": 107,
   "OpponentScore": 114,
   "W": 9,
   "L": 25
 },
 {
   "Game": 35,
   "Date": "Tue Dec 25 2018",
   "Location": "",
   "Opponent": "Milwaukee Bucks",
   "Result": "L",
   "TeamScore": 95,
   "OpponentScore": 109,
   "W": 9,
   "L": 26
 },
 {
   "Game": 36,
   "Date": "Thu Dec 27 2018",
   "Location": "@",
   "Opponent": "Milwaukee Bucks",
   "Result": "L",
   "TeamScore": 96,
   "OpponentScore": 112,
   "W": 9,
   "L": 27
 },
 {
   "Game": 37,
   "Date": "Sat Dec 29 2018",
   "Location": "@",
   "Opponent": "Utah Jazz",
   "Result": "L",
   "TeamScore": 97,
   "OpponentScore": 129,
   "W": 9,
   "L": 28
 },
 {
   "Game": 38,
   "Date": "Tue Jan 1 2019",
   "Location": "@",
   "Opponent": "Denver Nuggets",
   "Result": "L",
   "TeamScore": 108,
   "OpponentScore": 115,
   "W": 9,
   "L": 29
 },
 {
   "Game": 39,
   "Date": "Fri Jan 4 2019",
   "Location": "@",
   "Opponent": "Los Angeles Lakers",
   "Result": "W",
   "TeamScore": 119,
   "OpponentScore": 112,
   "W": 10,
   "L": 29
 },
 {
   "Game": 40,
   "Date": "Mon Jan 7 2019",
   "Location": "@",
   "Opponent": "Portland Trail Blazers",
   "Result": "L",
   "TeamScore": 101,
   "OpponentScore": 111,
   "W": 10,
   "L": 30
 },
 {
   "Game": 41,
   "Date": "Tue Jan 8 2019",
   "Location": "@",
   "Opponent": "Golden State Warriors",
   "Result": "L",
   "TeamScore": 95,
   "OpponentScore": 122,
   "W": 10,
   "L": 31
 },
 {
   "Game": 42,
   "Date": "Fri Jan 11 2019",
   "Location": "",
   "Opponent": "Indiana Pacers",
   "Result": "L",
   "TeamScore": 106,
   "OpponentScore": 121,
   "W": 10,
   "L": 32
 },
 {
   "Game": 43,
   "Date": "Sun Jan 13 2019",
   "Location": "",
   "Opponent": "Philadelphia 76ers",
   "Result": "L",
   "TeamScore": 105,
   "OpponentScore": 108,
   "W": 10,
   "L": 33
 },
 {
   "Game": 44,
   "Date": "Thu Jan 17 2019",
   "Location": "@",
   "Opponent": "Washington Wizards",
   "Result": "L",
   "TeamScore": 100,
   "OpponentScore": 101,
   "W": 10,
   "L": 34
 },
 {
   "Game": 45,
   "Date": "Mon Jan 21 2019",
   "Location": "",
   "Opponent": "Oklahoma City Thunder",
   "Result": "L",
   "TeamScore": 109,
   "OpponentScore": 127,
   "W": 10,
   "L": 35
 },
 {
   "Game": 46,
   "Date": "Wed Jan 23 2019",
   "Location": "",
   "Opponent": "Houston Rockets",
   "Result": "L",
   "TeamScore": 110,
   "OpponentScore": 114,
   "W": 10,
   "L": 36
 },
 {
   "Game": 47,
   "Date": "Fri Jan 25 2019",
   "Location": "@",
   "Opponent": "Brooklyn Nets",
   "Result": "L",
   "TeamScore": 99,
   "OpponentScore": 109,
   "W": 10,
   "L": 37
 },
 {
   "Game": 48,
   "Date": "Sun Jan 27 2019",
   "Location": "",
   "Opponent": "Miami Heat",
   "Result": "L",
   "TeamScore": 97,
   "OpponentScore": 106,
   "W": 10,
   "L": 38
 },
 {
   "Game": 49,
   "Date": "Mon Jan 28 2019",
   "Location": "@",
   "Opponent": "Charlotte Hornets",
   "Result": "L",
   "TeamScore": 92,
   "OpponentScore": 101,
   "W": 10,
   "L": 39
 },
 {
   "Game": 50,
   "Date": "Wed Jan 30 2019",
   "Location": "",
   "Opponent": "Dallas Mavericks",
   "Result": "L",
   "TeamScore": 90,
   "OpponentScore": 114,
   "W": 10,
   "L": 40
 },
 {
   "Game": 51,
   "Date": "Fri Feb 1 2019",
   "Location": "",
   "Opponent": "Boston Celtics",
   "Result": "L",
   "TeamScore": 99,
   "OpponentScore": 113,
   "W": 10,
   "L": 41
 },
 {
   "Game": 52,
   "Date": "Sun Feb 3 2019",
   "Location": "",
   "Opponent": "Memphis Grizzlies",
   "Result": "L",
   "TeamScore": 84,
   "OpponentScore": 96,
   "W": 10,
   "L": 42
 },
 {
   "Game": 53,
   "Date": "Tue Feb 5 2019",
   "Location": "",
   "Opponent": "Detroit Pistons",
   "Result": "L",
   "TeamScore": 92,
   "OpponentScore": 105,
   "W": 10,
   "L": 43
 },
 {
   "Game": 54,
   "Date": "Fri Feb 8 2019",
   "Location": "@",
   "Opponent": "Detroit Pistons",
   "Result": "L",
   "TeamScore": 103,
   "OpponentScore": 120,
   "W": 10,
   "L": 44
 },
 {
   "Game": 55,
   "Date": "Sat Feb 9 2019",
   "Location": "",
   "Opponent": "Toronto Raptors",
   "Result": "L",
   "TeamScore": 99,
   "OpponentScore": 104,
   "W": 10,
   "L": 45
 },
 {
   "Game": 56,
   "Date": "Mon Feb 11 2019",
   "Location": "@",
   "Opponent": "Cleveland Cavaliers",
   "Result": "L",
   "TeamScore": 104,
   "OpponentScore": 107,
   "W": 10,
   "L": 46
 },
 {
   "Game": 57,
   "Date": "Wed Feb 13 2019",
   "Location": "",
   "Opponent": "Philadelphia 76ers",
   "Result": "L",
   "TeamScore": 111,
   "OpponentScore": 126,
   "W": 10,
   "L": 47
 },
 {
   "Game": 58,
   "Date": "Thu Feb 14 2019",
   "Location": "@",
   "Opponent": "Atlanta Hawks",
   "Result": "W",
   "TeamScore": 106,
   "OpponentScore": 91,
   "W": 11,
   "L": 47
 },
 {
   "Game": 59,
   "Date": "Fri Feb 22 2019",
   "Location": "",
   "Opponent": "Minnesota Timberwolves",
   "Result": "L",
   "TeamScore": 104,
   "OpponentScore": 115,
   "W": 11,
   "L": 48
 },
 {
   "Game": 60,
   "Date": "Sun Feb 24 2019",
   "Location": "",
   "Opponent": "San Antonio Spurs",
   "Result": "W",
   "TeamScore": 130,
   "OpponentScore": 118,
   "W": 12,
   "L": 48
 },
 {
   "Game": 61,
   "Date": "Tue Feb 26 2019",
   "Location": "",
   "Opponent": "Orlando Magic",
   "Result": "W",
   "TeamScore": 108,
   "OpponentScore": 103,
   "W": 13,
   "L": 48
 },
 {
   "Game": 62,
   "Date": "Thu Feb 28 2019",
   "Location": "",
   "Opponent": "Cleveland Cavaliers",
   "Result": "L",
   "TeamScore": 118,
   "OpponentScore": 125,
   "W": 13,
   "L": 49
 },
 {
   "Game": 63,
   "Date": "Sun Mar 3 2019",
   "Location": "@",
   "Opponent": "Los Angeles Clippers",
   "Result": "L",
   "TeamScore": 107,
   "OpponentScore": 128,
   "W": 13,
   "L": 50
 },
 {
   "Game": 64,
   "Date": "Mon Mar 4 2019",
   "Location": "@",
   "Opponent": "Sacramento Kings",
   "Result": "L",
   "TeamScore": 108,
   "OpponentScore": 115,
   "W": 13,
   "L": 51
 },
 {
   "Game": 65,
   "Date": "Wed Mar 6 2019",
   "Location": "@",
   "Opponent": "Phoenix Suns",
   "Result": "L",
   "TeamScore": 96,
   "OpponentScore": 107,
   "W": 13,
   "L": 52
 },
 {
   "Game": 66,
   "Date": "Sat Mar 9 2019",
   "Location": "",
   "Opponent": "Sacramento Kings",
   "Result": "L",
   "TeamScore": 94,
   "OpponentScore": 102,
   "W": 13,
   "L": 53
 },
 {
   "Game": 67,
   "Date": "Sun Mar 10 2019",
   "Location": "@",
   "Opponent": "Minnesota Timberwolves",
   "Result": "L",
   "TeamScore": 92,
   "OpponentScore": 103,
   "W": 13,
   "L": 54
 },
 {
   "Game": 68,
   "Date": "Tue Mar 12 2019",
   "Location": "@",
   "Opponent": "Indiana Pacers",
   "Result": "L",
   "TeamScore": 98,
   "OpponentScore": 103,
   "W": 13,
   "L": 55
 },
 {
   "Game": 69,
   "Date": "Fri Mar 15 2019",
   "Location": "@",
   "Opponent": "San Antonio Spurs",
   "Result": "L",
   "TeamScore": 83,
   "OpponentScore": 109,
   "W": 13,
   "L": 56
 },
 {
   "Game": 70,
   "Date": "Sun Mar 17 2019",
   "Location": "",
   "Opponent": "Los Angeles Lakers",
   "Result": "W",
   "TeamScore": 124,
   "OpponentScore": 123,
   "W": 14,
   "L": 56
 },
 {
   "Game": 71,
   "Date": "Mon Mar 18 2019",
   "Location": "@",
   "Opponent": "Toronto Raptors",
   "Result": "L",
   "TeamScore": 92,
   "OpponentScore": 128,
   "W": 14,
   "L": 57
 },
 {
   "Game": 72,
   "Date": "Wed Mar 20 2019",
   "Location": "",
   "Opponent": "Utah Jazz",
   "Result": "L",
   "TeamScore": 116,
   "OpponentScore": 137,
   "W": 14,
   "L": 58
 },
 {
   "Game": 73,
   "Date": "Fri Mar 22 2019",
   "Location": "",
   "Opponent": "Denver Nuggets",
   "Result": "L",
   "TeamScore": 93,
   "OpponentScore": 111,
   "W": 14,
   "L": 59
 },
 {
   "Game": 74,
   "Date": "Sun Mar 24 2019",
   "Location": "",
   "Opponent": "Los Angeles Clippers",
   "Result": "L",
   "TeamScore": 113,
   "OpponentScore": 124,
   "W": 14,
   "L": 60
 },
 {
   "Game": 75,
   "Date": "Thu Mar 28 2019",
   "Location": "",
   "Opponent": "Toronto Raptors",
   "Result": "L",
   "TeamScore": 92,
   "OpponentScore": 117,
   "W": 14,
   "L": 61
 },
 {
   "Game": 76,
   "Date": "Sat Mar 30 2019",
   "Location": "",
   "Opponent": "Miami Heat",
   "Result": "L",
   "TeamScore": 92,
   "OpponentScore": 100,
   "W": 14,
   "L": 62
 },
 {
   "Game": 77,
   "Date": "Mon Apr 1 2019",
   "Location": "",
   "Opponent": "Chicago Bulls",
   "Result": "W",
   "TeamScore": 113,
   "OpponentScore": 105,
   "W": 15,
   "L": 62
 },
 {
   "Game": 78,
   "Date": "Wed Apr 3 2019",
   "Location": "@",
   "Opponent": "Orlando Magic",
   "Result": "L",
   "TeamScore": 100,
   "OpponentScore": 114,
   "W": 15,
   "L": 63
 },
 {
   "Game": 79,
   "Date": "Fri Apr 5 2019",
   "Location": "@",
   "Opponent": "Houston Rockets",
   "Result": "L",
   "TeamScore": 96,
   "OpponentScore": 120,
   "W": 15,
   "L": 64
 },
 {
   "Game": 80,
   "Date": "Sun Apr 7 2019",
   "Location": "",
   "Opponent": "Washington Wizards",
   "Result": "W",
   "TeamScore": 113,
   "OpponentScore": 110,
   "W": 16,
   "L": 64
 },
 {
   "Game": 81,
   "Date": "Tue Apr 9 2019",
   "Location": "@",
   "Opponent": "Chicago Bulls",
   "Result": "W",
   "TeamScore": 96,
   "OpponentScore": 86,
   "W": 17,
   "L": 64
 },
 {
   "Game": 82,
   "Date": "Wed Apr 10 2019",
   "Location": "",
   "Opponent": "Detroit Pistons",
   "Result": "L",
   "TeamScore": 89,
   "OpponentScore": 115,
   "W": 17,
   "L": 65
 }
]

export default data
